name: test1

on:
  push:
    branches:
      - 'dev[0-9][0-9]'
      - dlv
      - acc
      
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: test
        run: echo "hello"
  
