name: Workflow A

on:
  push:
    branches: [ "main" ]

jobs:
  some_job:  
    runs-on: ubuntu-latest
    steps:
      - name: Some Step 
        run: echo "Hello!"

  job_producing_data:  
    runs-on: ubuntu-latest
    steps:
      - name: Some Step 
        run: |
            printf '{ 
              "run_id": "${{ github.run_id }}",  
              "run_number": "${{ github.run_number }}"
            }' >> context.json
      - uses: actions/upload-artifact@v4
        with:
          name: context.json
          path: ./
